
services:
  ops-grafana:
    image: grafana/grafana:latest
    container_name: ops-grafana
    restart: unless-stopped
    ports:
      - '9990:3000'
    volumes:
      - './config/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro'
      - './config/grafana/provisioning/dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml:ro'
      - './config/grafana/dashboards:/etc/grafana/dashboards:ro'
      - './data/grafana-storage:/var/lib/grafana'
    networks: ['app-monitoring']
  ops-prom-prometheus:
    image: prom/prometheus:latest
    container_name: ops-prometheus
    restart: unless-stopped
    ports:
      - '9991:9090'
    volumes:
      - './config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml'
      - './data/prometheus:/prometheus'
    networks: ['app-monitoring']
  ops-prom-node-exporter:
    image: prom/node-exporter:latest
    container_name: ops-prometheus-node-exporter
    volumes:
      - '/proc:/host/proc:ro'
      - '/sys:/host/sys:ro'
      - '/:/rootfs:ro'
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    ports:
      - '9992:9100'
    networks: ['app-monitoring']

networks:
  app-monitoring:
    driver: bridge
